COMPONENT = RssiAppC
# virtual machine 
# TINYOS_ROOT_DIR := /home/nes/Development/repositories/tinyos-main
# raspberry pi
TINYOS_ROOT_DIR := /home/diao/WSN/tinyos-main
CFLAGS += -I$(TINYOS_ROOT_DIR)/tos/lib/printf
CFLAGS += -DPRINTF_BUFFER_SIZE=512

include $(TINYOS_ROOT_DIR)/Makefile.include
